const activities = [
  {id:1,date:'01-28',sort:'2026-01-28',title:"CLASSYS Partners' Meeting in Paris 2026",type:'伙伴会议 / 渠道营销',group:'owned',place:'巴黎，法国',venue:'Renaissance Paris Nobel Tour Eiffel',desc:'回顾 2025 销售与营销，发布 2026 outlook、marketing plan 与 CIC update，并进行伙伴表彰。',data:'约 80 名欧洲及全球渠道伙伴受邀；内容含 CE-MDR 认证成果纪念 + 2026 欧洲扩张战略 + 全球营销方向（이데일리 2026-01-30）。Best Partner 获奖名单未公开。',products:'全球合作伙伴 · 销售、营销与 CIC 团队',source:'https://classys.co.kr/partners-meeting-in-paris/',confidence:'A · 官方邀请函 + 이데일리 2026-01-30',image:'assets/partners-paris.jpg'},
  {id:2,date:'01-29',sort:'2026-01-29',title:'CLASSYS Global Customer Summit in Paris 2026',type:'自办客户峰会 / 学术营销',group:'owned',place:'巴黎，法国',venue:'Pavillon Wagram',desc:'首届巴黎全球客户峰会，连接行业领袖、分享最佳实践，并围绕医学美学扩展可能性。',data:'约 160 名欧洲主要医师及 VIP 客户出席；主题"미용의료의 새로운 기준"（美业医疗新标准）；议程=Classys 全球愿景 + 2026 增长战略 + 欧洲医师临床数据/实操方案发表（이데일리 2026-01-30）。讲者姓名未公开。',products:'Ultraformer MPT · Volnewmer · Veloce',source:'https://classys.co.kr/cgcs-paris-2026/',confidence:'A · 官方邀请函 + 이데일리 2026-01-30',image:'assets/cgcs-paris.jpg'},
  {id:3,date:'01-29 — 01-31',sort:'2026-01-29',title:'IMCAS PARIS 2026',type:'国际展会 / 学术会议',group:'exhibition',place:'巴黎，法国',venue:'Palais des Congrès · Level 3 U358',desc:'面向国际医生与经销商展示设备和临床应用，形成巴黎活动周的专业会议触点。',data:'第 27 届，第三方报道 400+ 参展企业、2 万+ 医师及业界人士参会；Classys 以 CE-MDR 认证的 Volnewmer、Ultraformer MPT 为核心展品，并展出家用 HIFU「Lift2Glow」（마이데일리 2026-02-02）。',products:'Ultraformer MPT · Volnewmer · Lift2Glow',source:'https://classys.com/exhibitions/imcas-paris-2026/',confidence:'A · 官方英文官网 + 마이데일리 2026-02-02',image:'assets/cgcs-paris.jpg'},
  {id:4,date:'2026-02',sort:'2026-02-15',title:'Everesse 获 2026 K-Brand Awards',type:'奖项 / 产品 PR',group:'brand',place:'韩国 / 全球',venue:'K-Medical 类别',desc:'以 K-Medical 类别获奖强化 Volnewmer 的品牌与产品信任背书。',data:'官方 History 页原文："Everesse (Volnewmer), honored in the K-Medical category at the 2026 K-Brand Awards hosted by TV Chosun"。TV Chosun 官方颁奖站确认第 3 届 2026 K-Brand Awards，颁奖礼 2026-02-25 于首尔 The Plaza Hotel（tvchosunawards.co.kr）。除官方两处外无第三方报道细节。',products:'Everesse（Volnewmer）',source:'https://classys.com/company/history/',confidence:'A · 官方 History 页 + TV Chosun 颁奖官网',image:'assets/cgcs-paris.jpg'},
  {id:5,date:'2026-01',sort:'2026-01-15',title:'Ultraformer MPT 入选 Korea Brand Hall of Fame',type:'奖项 / 产品 PR',group:'brand',place:'韩国',venue:'皮肤美容医疗设备类别',desc:'以 Top Brand 荣誉强化 Ultraformer MPT 的产品认知与行业信任。',data:'连续第 3 年入选（2024-2026，동아일보 2026-01-22 特刊原文"3년 연속"）；主办方为韩国产业政策研究院（IPS）；同文披露 Shurink 系列累计设备销量突破 2 万台。',products:'Ultraformer MPT（Shurink Universe）',source:'https://classys.com/company/history/',confidence:'A · 동아일보 2026-01-22 + 官方 History 页'},
  {id:6,date:'02-28',sort:'2026-02-28',title:'CLASSYS Rise Program Seoul',type:'区域客户培育 / 医生教育',group:'owned',place:'首尔，韩国',venue:'Conrad Seoul · Studio 4 (6F)',desc:'通过本土客户培育项目开展品牌、临床与业务交流。',data:'官方定位"매출로 이어지는 클래시스 상담 노하우"（转化销售的咨询诀窍培训）；有 Event-us 报名页；人数与议程细节未公开。',products:'CLASSYS 产品组合 · 韩国医生与客户',source:'https://classys.co.kr/exhibitions/2026-클래시스-라이즈-프로그램-서울/',confidence:'A · 韩国官网活动页 + Event-us 报名页'},
  {id:7,date:'03-01',sort:'2026-03-01',title:'韩国皮肤肥胖整形学会春季学术大会',type:'展会 / 外部学术会议',group:'exhibition',place:'首尔，韩国',venue:'COEX 3F E Hall',desc:'官方参会 / 参展，触达皮肤、体形与整形专业受众。',data:'官方活动页确认时间场地；参会人数与展位活动未公开（无新闻稿）。',products:'CLASSYS 产品组合 · 韩国专业医生',source:'https://classys.co.kr/exhibitions/2026-한국피부비만성형학회-춘계학술대회/',confidence:'A · 韩国官网活动页（人数未公开）'},
  {id:8,date:'03-08',sort:'2026-03-08',title:'韩国肥胖美容学会春季学术大会（KOAT）',type:'展会 / 外部学术会议',group:'exhibition',place:'首尔，韩国',venue:'COEX E Hall & Conference Room',desc:'官方参会 / 参展，开展肥胖与医美专业交流。',data:'官方活动页确认时间场地；参会人数未公开。参考：2025 年 KOAT 春季大会有新闻稿（뉴시스 2025-04-14）。',products:'CLASSYS 产品组合 · KOAT 专业受众',source:'https://classys.co.kr/exhibitions/2026-대한비만미용학회-춘계학술대회-koat/',confidence:'A · 韩国官网活动页（人数未公开）'},
  {id:9,date:'03-11 — 03-12',sort:'2026-03-11',title:'CLASSYS Academy LATAM 2026',type:'学术培训 / Hands-on',group:'academy',place:'圣保罗，巴西',venue:'CLASSYS HQ（R. James Joule, 65）',desc:'两日理论与实操培训，面向医生、临床与经销商人员提供产品课程和证书支持。',data:'Day1 理论：Volnewmer / Ultraformer MPT / Secret Duo；Day2 实操：Ultraformer MPT、VOLFORMER、Volnewmer；报名表强制填写机构与身份（Doctor/Clinical/Distributor）并出证书；人数与讲师未公开。',products:'Volnewmer · Ultraformer MPT · Secret Duo',source:'https://classys.co.kr/classys-academy-in-latam-2026/',confidence:'A · 官方报名页及邀请函（人数未公开）',image:'assets/academy-latam.jpg'},
  {id:10,date:'03-19 — 03-20',sort:'2026-03-19',title:'CLASSYS Academy in Seoul',type:'学术培训 / 医生教育',group:'academy',place:'首尔，韩国',venue:'CLASSYS 总部 19、20 层',desc:'总部 Academy 培训，强化产品、治疗方案与临床交流。',data:'邀请函 OCR 所得讲师：Dr. Julia Chebotareva、Dr. Vorapot Siramangkhalanon、Dr. HyunHwa Kim（Reepot）、Dr. Kumiko Koromohara（Quadessy）；含证书/合影；参加人数未公开。',products:'Volnewmer · Ultraformer MPT · Reepot · Quadessy',source:'https://classys.co.kr/exhibitions/2026-classys-acedemy-in-seoul/',confidence:'A− · 韩国官网活动页 + 邀请函 OCR',image:'assets/academy-seoul.jpg'},
  {id:11,date:'03-19 — 03-22',sort:'2026-03-19',title:'KIMES 2026',type:'展会 / 医疗器械展',group:'exhibition',place:'首尔，韩国',venue:'COEX · 1F A210',desc:'面向医院、诊所、经销商与行业买家展示设备矩阵。',data:'第 41 届，第三方报道 7 万余名国内外观众（전자신문 2026-04-06，参展企业口径）；IR Book 1Q26 将 KIMES 列为 1Q 广告费驱动项。',products:'CLASSYS 产品组合',source:'https://classys.co.kr/exhibitions/2026-kimes-제41회-국제의료기기-병원설비전시회/',confidence:'A · 韩国官网活动页 + 전자신문 2026-04-06'},
  {id:12,date:'03-22',sort:'2026-03-22',title:'Global Customer Summit Seoul（CGCS 2026）',type:'自办客户峰会 / 渠道营销',group:'owned',place:'首尔，韩国',venue:'Grand Walkerhill Seoul · Vista Hall',desc:'面向全球客户与合作伙伴的年度交流活动，强化品牌愿景、渠道关系与产品沟通。',data:'第 2 届，约 500 名国内外医师、20 余国参加；讲者：Dr. Corinne Erickson（美国皮肤科，Everesse 临床）、황제완 원장（Volnewmer 论文共同作者）、Dr. Carl Cheng（台湾，Reepot 一年以上临床数据），并介绍 Quadessy；公司宣布将每年定期举办（한국경제 2026-03-24）。朴叙俊/蔡秀彬出席仅见于 klifejourney/mimint，未获主流财经媒体复核。',products:'全球客户 · 经销商 · 管理团队 · Everesse · Reepot · Quadessy',source:'https://classys.co.kr/exhibitions/2026-classys-global-customer-summit/',confidence:'A · 한국경제 2026-03-24 + 官方活动页',image:'assets/cgcs-paris.jpg'},
  {id:13,date:'03-26 — 03-28',sort:'2026-03-26',title:'AMWC Monaco 2026',type:'国际展会 / 学术会议',group:'exhibition',place:'摩纳哥',venue:'Grimaldi Forum · Ravel N12',desc:'在欧洲核心医美会议展示设备、临床应用与渠道支持。',data:'主办方 Post-Show Report：17,688 名与会者（13,087 代表 + 4,094 产业）、507 名讲者、地域覆盖欧洲 52%/南美 16% 等；Classys 展位活动细节未公开。',products:'Ultraformer MPT · Volnewmer',source:'https://classys.com/exhibitions/amwc-monaco-2026/',confidence:'A · 官方英文官网 + AMWC Post-Show Report',image:'assets/amwc.jpg'},
  {id:14,date:'03-27 — 03-31',sort:'2026-03-27',title:'AAD 2026',type:'国际展会 / 学术会议',group:'exhibition',place:'丹佛，美国',venue:'Colorado Convention Center · Booth 3756',desc:'面向皮肤科医生展示能量源设备与临床应用。',data:'展品=Everesse + Quadessy（2026.03 在美上市）+ Reepot（年内上市）+ Ultraformer MPT；举办 Everesse 美国皮肤科医师学术发表会；当地伙伴为 Cartessa；2026 为进入美国市场第 2 年（한국경제 2026-03-30）。AAD 2026 总参会人数未公开。',products:'Everesse · Quadessy · Reepot · Ultraformer MPT',source:'https://classys.com/exhibitions/aad-2026/',confidence:'A · 官方英文官网 + 한국경제 2026-03-30'},
  {id:15,date:'2026-03',sort:'2026-03-15',title:'MSCI ESG 评级 AAA',type:'企业品牌 / ESG 传播',group:'brand',place:'全球 / 韩国总部',venue:'MSCI ESG Rating',desc:'以 ESG 评级升级强化公司治理、可持续与长期合作信任。',data:'官方时间线：MSCI BBB(2023) → A(2024) → AAA(2026)；同期 KCGS A(2025)、Sustinvest AA(2025)；2026 年 AAA 未单独发新闻稿（History + ESG 页 + Sustainability Report 2025 可查）。',products:'CLASSYS 企业品牌',source:'https://classys.com/company/history/',confidence:'A− · 官方 History 与 ESG 页'},
  {id:16,date:'05-07 — 05-09',sort:'2026-05-07',title:'ASLMS 2026',type:'国际展会 / 学术会议',group:'exhibition',place:'萨凡纳，美国',venue:'Savannah Convention Center · Booth 524',desc:'参加激光医学与能量源技术专业交流。',data:'第 45 届；展品 Everesse + Quadessy 双轨 + Reepot（年内上市）+ Ultraformer MPT（计划 2027 年美国上市）；开幕前 Pre-session 讲者 Dr. Carl Cheng（Reepot 色素治疗、1 年以上临床数据）（이데일리 2026-05-11）。总参会人数未公开。注意：AAD 稿称 Ultraformer MPT"年内上市"、ASLMS 稿称"2027 年上市"，口径不一。',products:'Everesse · Quadessy · Reepot · Ultraformer MPT',source:'https://classys.com/exhibitions/aslms-2026/',confidence:'A · 官方英文官网 + 이데일리 2026-05-11',image:'assets/aslms.jpg'},
  {id:17,date:'06-19 — 06-21',sort:'2026-06-19',title:'IMCAS ASIA 2026',type:'国际展会 / 学术会议',group:'exhibition',place:'曼谷，泰国',venue:'The Athenee Hotel · Booth N23',desc:'面向亚洲皮肤科、整形外科与老化科学专家进行品牌与产品展示。',data:'官方活动页确认 Booth N23 与 The Athenee Hotel；展位活动与大会参会人数未公开。',products:'Ultraformer MPT · Volnewmer',source:'https://classys.com/exhibitions/imcas-asia-2026/',confidence:'A · 官方英文官网（人数未公开）',image:'assets/imcas-asia.jpg'},
  {id:18,date:'01-12 — 01-15',sort:'2026-01-12',title:'JP Morgan Healthcare Conference 2026',type:'行业会议 / 投资者与企业 PR',group:'brand',place:'旧金山，美国',venue:'The Westin St. Francis · PANELS',desc:'作为韩国企业首次主导 "Beyond K-Beauty" 专题讨论，向全球投资者和产业代表讲述韩国医美技术与增长逻辑。',data:'第 44 届，预计 8,000+ 与会者；JPM 遴选 10 个主题，Beyond K-Beauty 其一；主场室 200+ 座；Classys 为受邀 EBD 企业中唯一、韩国企业首次；panel 成员=김래희 마케팅본부장 + Dr. Mark Halsey（美国皮肤科）；官方披露 2030 目标营收 10 亿美元、OPM 50%+；Shurink 全球累计销量 2 万台+（官方新闻稿 uid=590/591/592）。',products:'Ultraformer · Volnewmer · Quadessy · CLASSYS 企业品牌',source:'https://classys.co.kr/?kboard_content_redirect=590',confidence:'A · 官方新闻稿三篇（2026-01-08/12/15）'},
  {id:19,date:'03-05',sort:'2026-03-05',title:'巴西 JL Health / Medsystems 收购完成',type:'市场扩张 / 企业 PR',group:'brand',place:'巴西 / 拉丁美洲',venue:'巴西、哥伦比亚、阿根廷直营网络',desc:'完成 JL Health 77.5% 股权收购并取得哥伦比亚、阿根廷分销公司 100% 股权，建立拉美直接分销与销售结构。',data:'官方数字：巴西美业器械市场 8 亿美元（全球第 4）、EBD 年增 15%+；Medsystems 客户 15,000+ 医院及美容机构、2024 营收约 1,350 亿韩元、调整后 EBITDA 169 亿；全现金收购、企业价值约 1,000 亿韩元；CEO Andrea Gaeta Lima（前 Allergan Aesthetics 巴西负责人）；2026 年预计并表增收约 500 亿韩元；南美法人员工 2026.03=206 人 → 06=256 人（uid=571/595 + IR Book 2Q26）。',products:'Ultraformer · Volnewmer · Quadessy · 15,000+ 客户触点',source:'https://classys.co.kr/?kboard_content_redirect=595',confidence:'A · 官方新闻稿 uid=571/595 + IR Book 2Q26',image:'assets/academy-latam.jpg'}
];

const activityInsights={
  1:{scale:'区域 / 专业圈层',audience:'全球合作伙伴、经销商、销售与市场团队',result:'约 80 名伙伴参会，发布 2026 outlook、营销计划与 CIC 更新，并完成伙伴表彰。',focus:'渠道政策、合作伙伴激励与 IMCAS 前置联动。'},
  2:{scale:'全球 / 自办峰会',audience:'行业领袖、医生、全球客户与渠道伙伴',result:'约 160 名欧洲医师与 VIP 出席，落地首届巴黎 Global Customer Summit。',focus:'首次举办后的持续性、讲者质量与客户转化。'},
  3:{scale:'全球 / 大型专业展会',audience:'皮肤科及整形医生、诊所决策者、国际经销商',result:'在 Level 3 U358 展示 Ultraformer MPT 与 Volnewmer，并展出家用 Lift2Glow。',focus:'巴黎三场活动的线索协同与明星产品曝光。'},
  4:{scale:'品牌 / 产品 PR',audience:'行业客户、渠道与潜在消费者',result:'Everesse 在 K-Medical 类别获得 2026 K-Brand Awards（TV Chosun 主办）。',focus:'奖项如何转化为医生采用与终端品牌认知。'},
  5:{scale:'品牌 / 产品 PR',audience:'韩国医美行业与终端市场',result:'Ultraformer MPT 获皮肤美容医疗设备类别 Top Brand 荣誉，连续第 3 年。',focus:'头部产品荣誉密集，竞品需避开泛化品牌对抗。'},
  6:{scale:'区域 / 客户培育',audience:'韩国医生、诊所客户与业务合作方',result:'在 Conrad Seoul 完成本土客户培育与临床业务交流。',focus:'区域项目是否形成复购、装机和医生社群。'},
  7:{scale:'区域 / 专业学会',audience:'皮肤、肥胖管理与整形专业医生',result:'在 COEX 专业学会触达韩国细分临床圈层。',focus:'产品与细分适应症的对应方式。'},
  8:{scale:'区域 / 专业学会',audience:'肥胖管理、体形与医美专业医生',result:'通过 KOAT 春季大会完成专业交流与产品触达。',focus:'体形管理场景和联合治疗内容。'},
  9:{scale:'区域 / 两日培训',audience:'拉美医生、临床人员与经销商团队',result:'完成理论、实操与证书支持，覆盖三项重点产品。',focus:'培训与巴西直营网络、后续装机的协同。'},
  10:{scale:'区域 / 总部培训',audience:'医生与临床工作人员',result:'在首尔总部开展两日产品、方案与临床培训，4 位海外讲师授课。',focus:'课程人数和认证路径尚待公开补证。'},
  11:{scale:'大型 / 综合医疗器械展',audience:'医院、诊所、经销商、采购与行业买家',result:'以 1F A210 展位集中展示 Classys 设备矩阵。',focus:'综合设备组合曝光与韩国渠道线索获取。'},
  12:{scale:'全球 / 自办峰会',audience:'全球客户、经销商和管理团队',result:'约 500 名医师、20 余国出席，3 位国际讲者 + Quadessy 介绍，宣布年度化。',focus:'明星到场信息仅两来源，主流媒体未复核。'},
  13:{scale:'全球 / 大型专业展会',audience:'医美医生、诊所经营者、欧洲渠道伙伴',result:'在 Ravel N12 展位展示临床应用与渠道支持。',focus:'欧洲核心市场的产品采用与渠道扩张。'},
  14:{scale:'全球 / 大型专业展会',audience:'皮肤科医生、研究者与美国医疗机构',result:'在 Booth 3756 展示 Everesse/Quadessy/Reepot，并举办美国皮肤科学术发表会。',focus:'美国准入前的医生认知与临床证据储备。'},
  15:{scale:'品牌 / 企业信誉',audience:'投资者、合作伙伴与企业客户',result:'MSCI ESG 评级提升至 AAA（2023 BBB → 2024 A → 2026 AAA）。',focus:'ESG 背书能否进入渠道合作与采购决策。'},
  16:{scale:'全球 / 大型专业会议',audience:'激光医学、能量源技术医生与研究人员',result:'以 Booth 524 进入高专业度激光医学交流场，Pre-session 由 Dr. Carl Cheng 主讲。',focus:'激光与能量源组合的技术差异和论文证据。'},
  17:{scale:'全球 / 亚洲专业展会',audience:'亚洲皮肤科、整形外科与抗衰老专家',result:'在 Booth N23 展示 Ultraformer MPT 与 Volnewmer。',focus:'亚洲区域渠道覆盖及明星产品重复曝光效率。'},
  18:{scale:'全球 / 8,000+ 行业会议',audience:'全球投资者、医药生物与医疗产业管理者',result:'韩国企业首次主导 Beyond K-Beauty PANELS 讨论，主会场 200+ 座。',focus:'将 K-Beauty 叙事升级为资本市场和产业影响力。'},
  19:{scale:'战略市场扩张',audience:'拉美诊所、医生、经销网络与潜在客户',result:'取得 JL Health 控股权及哥伦比亚、阿根廷分销公司全部股权，公开称获得 15,000+ 客户触点。',focus:'直营化将加速 Volnewmer、Quadessy 导入，并强化拉美教育与服务。'}
};
const activityPurposes={
  1:'面向全球经销商和合作伙伴的年度渠道会议，用于统一销售目标、市场计划和合作政策。',
  2:'Classys 自己举办的客户与学术峰会，通过专家交流、产品内容和客户社交强化品牌关系。',
  3:'全球大型医学美容与抗衰老大会，品牌通过展台和学术交流接触医生、诊所及国际经销商。',
  4:'围绕产品获奖开展的品牌公关传播，用第三方奖项提升市场认知和产品可信度。',
  5:'韩国品牌评选类传播活动，用 Top Brand 荣誉强化 Ultraformer MPT 的头部产品形象。',
  6:'面向韩国本地医生和客户的关系培育活动，结合产品、临床和业务沟通促进客户合作。',
  7:'韩国皮肤、肥胖管理和整形领域的专业学术会议，参会品牌可接触细分专科医生。',
  8:'聚焦肥胖管理、体形和医学美容的韩国专业会议，用于临床交流和产品场景展示。',
  9:'面向拉美医生、临床人员和经销商的两日培训，包含产品理论、实操练习和证书支持。',
  10:'在首尔总部举办的医生培训项目，用于讲解产品、治疗方案和临床操作。',
  11:'韩国大型综合医疗器械展，面向医院、诊所、采购和经销商集中展示完整设备组合。',
  12:'面向全球客户和合作伙伴的年度品牌峰会，用于分享品牌方向、产品信息并维护渠道关系。',
  13:'欧洲重要医学美容与抗衰老大会，品牌通过展台接触医生、诊所经营者和欧洲渠道商。',
  14:'美国皮肤科学会年度会议，是品牌接触美国皮肤科医生、研究者和医疗机构的重要专业活动。',
  15:'企业信誉类公关传播，通过 ESG 评级展示公司治理、可持续发展和长期合作能力。',
  16:'激光医学和能量源技术专业会议，主要面向相关医生、研究人员及技术型行业受众。',
  17:'面向亚洲皮肤科、整形外科和抗衰老专家的医学美容大会，是 Classys 覆盖亚洲医生和渠道的展会。',
  18:'全球大型医药与医疗投资行业会议，Classys 借助专题讨论向投资者和产业管理者传播企业增长故事。',
  19:'通过收购本地分销集团建立拉美直营网络的市场扩张动作，同时配合企业公关向市场传递区域增长计划。'
};
activities.forEach(a=>Object.assign(a,activityInsights[a.id],{purpose:activityPurposes[a.id]}));
const groupLabels={exhibition:'展会 / 会议',owned:'自办活动',academy:'Academy',brand:'品牌 / 扩张'};
let activeFilter='all',ascending=true;
const grid=document.querySelector('#activity-grid'),search=document.querySelector('#search'),dialog=document.querySelector('#detail-dialog');
function render(){
  const query=search.value.trim().toLowerCase();
  const list=activities.filter(a=>(activeFilter==='all'||a.group===activeFilter)&&[a.title,a.place,a.products,a.type].join(' ').toLowerCase().includes(query)).sort((a,b)=>(ascending?1:-1)*a.sort.localeCompare(b.sort));
  grid.innerHTML=list.map(a=>`<article class="activity-card" tabindex="0" data-id="${a.id}" aria-label="查看 ${a.title} 详情"><div class="image ${a.image?'':'placeholder'}" ${a.image?`style="background-image:url('${a.image}')"`:''}><span class="badge">${groupLabels[a.group]}</span><span class="scale-badge">${a.scale||''}</span></div><div class="body"><div class="date-place"><span>${a.date}</span><span>${a.place}</span></div><h3>${a.title}</h3><dl class="activity-facts"><div class="purpose"><dt>活动说明</dt><dd>${a.purpose||''}</dd></div><div><dt>Classys 动作</dt><dd>${a.desc}</dd></div>${a.data?`<div class="focus"><dt>数据支撑</dt><dd>${a.data}</dd></div>`:''}<div><dt>${a.group==='exhibition'?'参会类型':'主要受众'}</dt><dd>${a.audience||''}</dd></div><div><dt>公开结果</dt><dd>${a.result||''}</dd></div><div class="focus"><dt>关注点</dt><dd>${a.focus||''}</dd></div></dl><div class="card-foot"><span class="products">${a.products}</span><span class="open-icon">↗</span></div></div></article>`).join('');
  document.querySelector('#result-count').textContent=`${list.length} 条记录`;
  document.querySelector('#empty').style.display=list.length?'none':'block';
}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));
search.addEventListener('input',render);
document.querySelector('#sort-btn').addEventListener('click',e=>{ascending=!ascending;e.currentTarget.textContent=`日期：${ascending?'从早到晚':'从晚到早'} ↕`;render()});
function openDetail(id){const a=activities.find(x=>x.id===id);document.querySelector('#dialog-content').innerHTML=`<div class="dialog-inner"><div class="dialog-media" ${a.image?`style="background-image:url('${a.image}')"`:''}></div><div class="dialog-body"><span class="type">${groupLabels[a.group]} · ${a.type}</span><h2>${a.title}</h2><div class="dialog-meta"><div><span>时间</span>${a.date}</div><div><span>地点 / 市场</span>${a.place}</div><div><span>会场 / 展位</span>${a.venue}</div><div><span>规模</span>${a.scale||''}</div></div><div class="dialog-detail"><div><span>这个活动是做什么的</span><p>${a.purpose||''}</p></div><div><span>Classys 开展的内容</span><p>${a.desc}</p></div>${a.data?`<div class="focus"><span>数据支撑</span><p>${a.data}</p></div>`:''}<div><span>受众 / 参会类型</span><p>${a.audience||''}</p></div><div><span>公开结果</span><p>${a.result||''}</p></div><div class="focus"><span>竞争关注点</span><p>${a.focus||''}</p></div></div><div class="dialog-products"><strong>重点产品 / 人物</strong><br>${a.products}</div><a class="dialog-source" href="${a.source}" target="_blank" rel="noreferrer">查看官方来源 <span>↗</span></a><p class="confidence"><b>${a.confidence}</b></p></div></div>`;dialog.showModal()}
grid.addEventListener('click',e=>{const card=e.target.closest('.activity-card');if(card)openDetail(Number(card.dataset.id))});
grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.activity-card'))openDetail(Number(e.target.dataset.id))});
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
render();
